[package]
name = "res"
version = "0.1.0"
authors = ["matthew-gries <gries.m@husky.neu.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
