pub use memory::Memory;
pub use main_memory::MainMemory;
pub use video_memory::VideoMemory;

const NAMETABLE_WIDTH: usize = 32;
const NAMETABLE_HEIGHT: usize = 30;
const PALETTE_WIDTH: usize = 8;
const PALETTE_HEIGHT: usize = 8;

/// The data type representing the 256*240 pixel screen generated by the PPU.
pub type RenderedScreen = [[u8; NAMETABLE_HEIGHT*PALETTE_HEIGHT] NAMETABLE_WIDTH*PALETTE_WIDTH];

/// Undergo one PPU cycle and render the screen given the data in the CPU memory and PPU memory.
pub fn render_screen(cpu_mem: &MainMemory, ppu_mem: &VideoMemory) -> RenderedScreen {
    [[0; NAMETABLE_HEIGHT*PALETTE_HEIGHT] NAMETABLE_WIDTH*PALETTE_WIDTH];
}